#!/bin/bash
# Remember to do turing$ chmod 755 SampleShellScript.sh
# to make it executable; 
#
# To run:  turing$ ./SampleShellScript.sh
# Create the textbook example tables in your own database on turing
# Replace "sgauch" with your own username
mysql <<EOFMYSQL
use rgw007;

CREATE TABLE DEPT (
    DEPT_CODE CHAR(4) PRIMARY KEY,
    DEPT_NAME VARCHAR(50) NOT NULL,
    ROOM_NUM INT NOT NULL,
    BUILDING VARCHAR(50) NOT NULL
);

CREATE TABLE ROOM (
    ROOM_NUM INT NOT NULL,
    BUILDING VARCHAR(50) NOT NULL,
    CAPACITY INT CHECK (CAPACITY > 0),
    ROOM_TYPE VARCHAR(15),
    PRIMARY KEY (ROOM_NUM, BUILDING)
);

CREATE TABLE PROFESSOR (
    PROF_ID INT PRIMARY KEY,
    PROF_NAME VARCHAR(50) NOT NULL,
    RANK_TITLE VARCHAR(20),
    DEPT_CODE CHAR(4) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FOREIGN KEY (DEPT_CODE)
        REFERENCES DEPT(DEPT_CODE)
        ON DELETE RESTRICT
);

CREATE TABLE COURSE (
    DEPT_CODE CHAR(4) NOT NULL,
    COURSE_NUM VARCHAR(5) NOT NULL,
    COURSE_NAME VARCHAR(50) NOT NULL,
    CREDIT INT NOT NULL CHECK (CREDIT BETWEEN 1 AND 6),
    PRIMARY KEY (DEPT_CODE, COURSE_NUM),
    FOREIGN KEY (DEPT_CODE)
        REFERENCES DEPT(DEPT_CODE)
        ON DELETE RESTRICT
);

CREATE TABLE SECTION (
    SID INT PRIMARY KEY,
    DEPT_CODE CHAR(4) NOT NULL,
    COURSE_NUM VARCHAR(5) NOT NULL,
    PROF_ID INT,
    ROOM_NUM INT,
    BUILDING VARCHAR(50),
    DAYS VARCHAR(7),
    START TIME,
    END TIME,
    START_DAY DATE NOT NULL,
    END_DAY DATE NOT NULL,
    MAX_ENROLLMENT INT CHECK (MAX_ENROLLMENT >= 0),
    CURRENT_ENROLLMENT INT DEFAULT 0 CHECK (CURRENT_ENROLLMENT >= 0),
    CHECK (CURRENT_ENROLLMENT <= MAX_ENROLLMENT),

    FOREIGN KEY (DEPT_CODE, COURSE_NUM)
        REFERENCES COURSE(DEPT_CODE, COURSE_NUM)
        ON DELETE RESTRICT,

    FOREIGN KEY (PROF_ID)
        REFERENCES PROFESSOR(PROF_ID)
        ON DELETE CASCADE,

    FOREIGN KEY (ROOM_NUM, BUILDING)
        REFERENCES ROOM(ROOM_NUM, BUILDING)
        ON DELETE RESTRICT
);

SHOW TABLES;
EOFMYSQL