#!/bin/bash

mysql <<EOFMYSQL
use rgw007;

DESC DEPT;
DESC ROOM;
DESC PROFESSOR;
DESC COURSE;
DESC SECTION;

SELECT * FROM  DEPT;
SELECT * FROM  ROOM;
SELECT * FROM  PROFESSOR;
SELECT * FROM  COURSE;
SELECT * FROM  SECTION;

# Lowest Capacity Room
SELECT BUILDING, ROOM_NUM, CAPACITY
FROM ROOM
WHERE CAPACITY = (
    SELECT MIN(CAPACITY)
    FROM ROOM
);

# Open CSCE Electives
SELECT s.COURSE_NUM,
       s.DEPT_CODE,
       (s.MAX_ENROLLMENT - s.CURRENT_ENROLLMENT) AS AVAILABLE_SEATS
FROM SECTION s
JOIN COURSE c
    ON s.COURSE_NUM = c.COURSE_NUM
    AND s.DEPT_CODE = c.DEPT_CODE
WHERE s.DEPT_CODE = 'CSCE'
    AND s.COURSE_NUM >= 4000
    AND c.CREDIT >= 3
    AND s.CURRENT_ENROLLMENT < s.MAX_ENROLLMENT;

# Students Per Professor
SELECT PROF_NAME, SUM(MAX_ENROLLMENT) AS MAX_STUDENTS
FROM SECTION s
JOIN PROFESSOR p
    ON s.PROF_ID = p.PROF_ID
GROUP BY p.PROF_NAME;

# Associate Professors
SELECT  p.PROF_NAME,
        p.RANK_TITLE AS PROF_RANK,
        d.DEPT_NAME,
        d.BUILDING AS DEPT_BUILDING
FROM PROFESSOR p
JOIN DEPT d
    ON p.DEPT_CODE = d.DEPT_CODE
JOIN SECTION s
    ON p.PROF_ID = s.PROF_ID
GROUP BY p.PROF_ID, p.PROF_NAME, p.RANK_TITLE, d.DEPT_NAME, d.BUILDING
HAVING p.RANK_TITLE IN ('Associate Professor', 'Professor')
    AND COUNT(*) >= 1
    AND COUNT(*) = SUM(
        CASE
            WHEN s.BUILDING = d.BUILDING THEN 1
            ELSE 0
        END
    );

# Insert
INSERT INTO COURSE (DEPT_CODE,
                    COURSE_NUM,
                    COURSE_NAME,
                    CREDIT )
VALUES ('CSCE',
        4013,
        'Computer Forensics',
        3);
INSERT INTO SECTION (
    SID,
    DEPT_CODE,
    COURSE_NUM,
    PROF_ID,
    ROOM_NUM,
    BUILDING,
    DAYS,
    START,
    END,
    START_DAY,
    END_DAY,
    MAX_ENROLLMENT,
    CURRENT_ENROLLMENT
)
VALUES (
    (SELECT MAX(SID) + 1 FROM SECTION),
    'CSCE',
    4013,
    (SELECT PROF_ID FROM PROFESSOR WHERE PROF_NAME = 'Brajendra Panda'),
    239,
    'JBHT',
    NULL,
    NULL,
    NULL,
    '2023-08-21',
    '2023-12-07',
    25,
    0
);

SELECT s.*
FROM SECTION s
JOIN PROFESSOR p
    ON s.PROF_ID = p.PROF_ID
WHERE p.PROF_NAME = 'Brajendra Panda';

UPDATE SECTION
SET MAX_ENROLLMENT = 100,
    CURRENT_ENROLLMENT = 100
WHERE DEPT_CODE = 'CSCE'
    AND COURSE_NUM = '2004';

SELECT *
FROM SECTION
WHERE DEPT_CODE = 'CSCE'
    AND COURSE_NUM = '2004';

SELECT c.COURSE_NUM, c.COURSE_NAME, p.PROF_NAME
FROM COURSE c
JOIN SECTION s
    ON c.DEPT_CODE = s.DEPT_CODE
    AND c.COURSE_NUM = s.COURSE_NUM
JOIN PROFESSOR p
    ON s.PROF_ID = p.PROF_ID
WHERE c.DEPT_CODE = 'CSCE'
    AND c.COURSE_NUM LIKE '4%';

DELETE FROM PROFESSOR
WHERE PROF_NAME = 'Alexander Nelson';

SELECT c.COURSE_NUM, c.COURSE_NAME, p.PROF_NAME
FROM COURSE c
JOIN SECTION s
    ON c.DEPT_CODE = s.DEPT_CODE
    AND c.COURSE_NUM = s.COURSE_NUM
JOIN PROFESSOR p
    ON s.PROF_ID = p.PROF_ID
WHERE c.DEPT_CODE = 'CSCE'
    AND c.COURSE_NUM LIKE '4%';

EOFMYSQL